### ISSUE TITLE
Unable to setup smartir fan in next HA version (2022.4.b04)

### ISSUE THREAD

**Issue by aidbish** [smartHomeHub/SmartIR#817]
**Home Assistant version**
2022.4.b04
**SmartIR version**
1.17.5
**SmartIR configuration**

fan:
  - platform: smartir
    name: Master Bedroom fan
    unique_id: master_bedroom_fam
    device_code: 1600
    controller_data: remote.broadlinkrmpro_remote
```yaml



```

**Describe the bug**

The fan is unable to be setup in upcoming HA version. error listed below

**Debug log**
Logger: homeassistant.config
Source: custom_components/smartir/fan.py:8
Integration: smartir ([documentation](https://github.com/smartHomeHub/SmartIR))
First occurred: 9:23:04 PM (1 occurrences)
Last logged: 9:23:04 PM

Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/smartir/fan.py", line 8, in <module>
    from homeassistant.components.fan import (
ImportError: cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)
```text

Add your logs here.

```

**Additional context**

**Comment by Gio76** [comment]
The above issue is also occurring with **version 2022.4.0**

**Comment by agneevX** [comment]
Relevant Home Assistant PR: https://github.com/home-assistant/core/pull/67743

**Comment by ronjtaylor** [comment]
I got these warnings when I ran Check Home Assistant Configuration on 2.22.04.0

testing configuration at /tmp/config
INFO:homeassistant.helpers.storage:Migrating core.entity_registry storage from 1.5 to 1.6
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
WARNING:homeassistant.components.integration.sensor:The 'unit' option is deprecated, please remove it from your configuration
Failed config
  General Errors: 
    - Platform error fan.smartir - cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/local/lib/python3.9/site-packages/homeassistant/components/fan/__init__.py)
[06:57:10] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.

**Comment by LeandroIssa** [comment]
I have the same problem, does anyone know how to solve it?
@vassilis-panos do you have any idea?

Platform error fan.smartir - cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)

**Comment by aidbish** [comment]
> I have the same problem, does anyone know how to solve it? @vassilis-panos do you have any idea?
> 
> Platform error fan.smartir - cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/**init**.py)

Until  SmartIR is updated to work with latest HA version, the only solution is to rollback to previous version of HA

**Comment by h3nrytan** [comment]
Modifying with code below to custom_components/smartir/fan.py seem to work for me. Credit to https://github.com/al-one/hass-xiaomi-miot/commit/1c919bf8128c3b514ae3662b5c626a69768d00c1

```
from homeassistant.components.fan import (
    FanEntity, PLATFORM_SCHEMA,
    DIRECTION_REVERSE, DIRECTION_FORWARD,
    SUPPORT_SET_SPEED, SUPPORT_DIRECTION, SUPPORT_OSCILLATE, ATTR_OSCILLATING )

try:
    # hass 2022.4.0b0+
    from homeassistant.components.fan import ATTR_SPEED, SPEED_OFF, SPEED_LOW, SPEED_MEDIUM, SPEED_HIGH
except ImportError:
    ATTR_SPEED = "speed"
    SPEED_OFF = 'off'
    SPEED_LOW = "low"
    SPEED_MEDIUM = "medium"
    SPEED_HIGH = "high"
```

**Comment by LeandroIssa** [comment]
> Modifying with code below to custom_components/smartir/fan.py seem to work for me. Credit to [al-one/hass-xiaomi-miot@1c919bf](https://github.com/al-one/hass-xiaomi-miot/commit/1c919bf8128c3b514ae3662b5c626a69768d00c1)
> 
> ```
> from homeassistant.components.fan import (
>     FanEntity, PLATFORM_SCHEMA,
>     DIRECTION_REVERSE, DIRECTION_FORWARD,
>     SUPPORT_SET_SPEED, SUPPORT_DIRECTION, SUPPORT_OSCILLATE, ATTR_OSCILLATING )
> 
> try:
>     # hass 2022.4.0b0+
>     from homeassistant.components.fan import ATTR_SPEED, SPEED_OFF, SPEED_LOW, SPEED_MEDIUM, SPEED_HIGH
> except ImportError:
>     ATTR_SPEED = "speed"
>     SPEED_OFF = 'off'
>     SPEED_LOW = "low"
>     SPEED_MEDIUM = "medium"
>     SPEED_HIGH = "high"
> ```

Where in the file does this need to be added? Could you share your fan.py file already with the change? Thank you!

**Comment by h3nrytan** [comment]
> > Modifying with code below to custom_components/smartir/fan.py seem to work for me. Credit to [al-one/hass-xiaomi-miot@1c919bf](https://github.com/al-one/hass-xiaomi-miot/commit/1c919bf8128c3b514ae3662b5c626a69768d00c1)
> > ```
> > from homeassistant.components.fan import (
> >     FanEntity, PLATFORM_SCHEMA,
> >     DIRECTION_REVERSE, DIRECTION_FORWARD,
> >     SUPPORT_SET_SPEED, SUPPORT_DIRECTION, SUPPORT_OSCILLATE, ATTR_OSCILLATING )
> > 
> > try:
> >     # hass 2022.4.0b0+
> >     from homeassistant.components.fan import ATTR_SPEED, SPEED_OFF, SPEED_LOW, SPEED_MEDIUM, SPEED_HIGH
> > except ImportError:
> >     ATTR_SPEED = "speed"
> >     SPEED_OFF = 'off'
> >     SPEED_LOW = "low"
> >     SPEED_MEDIUM = "medium"
> >     SPEED_HIGH = "high"
> > ```
> 
> Where in the file does this need to be added? Could you share your fan.py file already with the change? Thank you!
[fan.zip](https://github.com/smartHomeHub/SmartIR/files/8439929/fan.zip)

here you go!

**Comment by aidbish** [comment]
1.17.6 has been released, update should resolve the error

**Comment by Gio76** [comment]
I can confirm that 1.17.6 solves the issue for me

**Comment by ronjtaylor** [comment]
I manually updated to smartir 1.17.6 on the 6th April and have been clearing errors in logs, restarting etc
This version of smartir was supposed to fix it according to above comments

I am currently on 2022.04.0 of HA
Showing version from __init__.py
DOMAIN = 'smartir'
VERSION = '1.17.6'
I still have this error
From_ my Log File

Logger: homeassistant.setup
Source: setup.py:298
First occurred: 6:24:03 AM (1 occurrences)
Last logged: 6:24:03 AM

Unable to prepare setup for platform sonoff.fan: Platform not found (cannot import name 'SPEED_LOW' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).

All my fans work ( 3 x sonoff.iFan03, and one RF 433MHz Eagle where I created my own json file) 

Not sure where the error is coming from?
